name: TWRP

on:
  workflow_dispatch:
  push:
    branches:
      - 'android-12.1'
    paths:
      - 'version.mk'

jobs:
  build:
    name: Build TWRP by ${{ github.actor }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Prepare the environment
      run: |
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo apt-get -y install gperf gcc-multilib g++-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libtinfo5 libsdl1.2-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static python-is-python3 python3 git curl

    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install Git-Repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize Repo
      run: |
        mkdir -p twrp
        cd twrp
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

    - name: Repo Sync
      run: |
        cd twrp
        repo sync -j$(nproc --all) --force-sync

    - name: Clone Device Tree
      run: |
        cd twrp
        git clone https://github.com/${{ github.repository }}.git -b android-12.1 ./device/realme/nashc
        cd device/realme/nashc
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Building Image
      run: |
        cd twrp
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_nashc-eng && make clean && make recoveryimage -j$(nproc --all)
        cd out/target/product/nashc
        mv recovery.img recovery-${{ github.run_id }}.img
        echo "Done building your recovery-${{ github.run_id }}.img"

    - name: Set Properties
      run: |
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        echo -e \
        "
        ## Test Build for Realme 8 (nashc) with Decryption Fixes
        * Fixed Trustonic TEE & Keymaster HAL in VINTF manifest
        * Fixed /mnt/vendor/persist mount
        * Added FBE v2 policy
        " > changelog.txt

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          twrp/out/target/product/nashc/recovery-${{ github.run_id }}.img
        name: TWRP Test Build for Realme 8 (nashc) // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body_path: changelog.txt
